In [2]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * 
                                            sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(10000):
        nn.feedforward()
        nn.backprop()


    print(nn.weights1) # 'blue' layer  [hidden]
    print()
    print(nn.weights2) # 'green' layer [output]
    print()
    nn.feedforward()   # this was missing earlier, thanks to Man Sun for noticing!
    print(nn.output)   # predictions

[[ 4.87187155  4.07210112 -3.08586121  6.3447932 ]
 [-2.48549953  3.98718328  5.04942446  6.42675095]
 [ 0.54278484 -6.16626257  1.07630627 -2.20534486]]

[[-4.70886981]
 [-8.29058452]
 [-4.78846468]
 [11.33855792]]

[[0.00431578]
 [0.99306052]
 [0.99329078]
 [0.00734108]]
